spring:
  application:
    name: user-service

server:
  port: 8001
  connection-timeout: 30s
  tomcat:
    max-threads: 20

datasource:
  base:
    jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: MSVC_BASE
    password: vd5qGSMu
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initialSize: 1 
    minIdle: 5 
    maxIdle: 5 
    maxActive: 20 
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000 
    minEvictableIdleTimeMillis: 300000 
    validationQuery: select 1 from dual 
    testWhileIdle: true
